- name: articles
  color: 55c550
  description: articles
  aliases: []
- name: automerge
  color: 0E8A16
  description: 'https://github.com/apps/mergery'
  aliases: []
- name: aws
  color: E08634
  description: AWS
  aliases: []
- name: bug
  color: d73a4a
  description: "Something isn't working"
  aliases: []
- name: chef
  color: 14C268
  description: Chef
  aliases: []
- name: datadog
  color: 632ca6
  description: Datadog
  aliases: []
- name: dependencies
  color: 0366d6
  description: 'Pull requests that update a dependency file'
  aliases: []
- name: docker
  color: 0052CC
  description: Docker
  aliases: []
- name: documentation
  color: 0075ca
  description: 'Improvements or additions to documentation'
  aliases: []
- name: duplicate
  color: cfd3d7
  description: 'This issue or pull request already exists'
  aliases: []
- name: enhancement
  color: a2eeef
  description: 'New feature or request'
  aliases: []
- name: github
  color: '000000'
  description: GitHub
  aliases: []
- name: github_actions
  color: '000000'
  description: 'Pull requests that update GitHub Actions code'
  aliases: []
- name: github_app
  color: 08B4B2
  description: 'GitHub App'
  aliases: []
- name: 'good first issue'
  color: 7057ff
  description: 'Good for newcomers'
  aliases: []
- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'
  aliases: []
- name: invalid
  color: e4e669
  description: "This doesn't seem right"
  aliases: []
- name: javascript
  color: FBCA04
  description: JavaScript
  aliases: []
- name: labels
  color: fef2c0
  description: labels
  aliases: []
- name: pagerduty
  color: 0E8A16
  description: PagerDuty
  aliases: []
- name: question
  color: d876e3
  description: 'Further information is requested'
  aliases: []
- name: rails
  color: B60205
  description: 'Ruby on Rails'
  aliases: []
- name: ruby
  color: B60205
  description: Ruby
  aliases: []
- name: size/L
  color: A14C05
  description: 'https://github.com/apps/pull-request-size'
  aliases: []
- name: size/M
  color: 7F7203
  description: 'https://github.com/apps/pull-request-size'
  aliases: []
- name: size/S
  color: 5D9801
  description: 'https://github.com/apps/pull-request-size'
  aliases: []
- name: size/XS
  color: 3CBF00
  description: 'https://github.com/apps/pull-request-size'
  aliases: []
- name: slack
  color: 76A2DD
  description: Slack
  aliases: []
- name: wontfix
  color: ffffff
  description: 'This will not be worked on'
  aliases: []
