- name: articles
  color: 4D6626
  description: Articles
  aliases: []
- name: automerge
  color: 0E8A16
  description: 'https://github.com/apps/mergery'
  aliases: []
- name: aws
  color: E08634
  description: AWS
  aliases: []
- name: blog
  color: 36ABBD
  description: null
  aliases: []
- name: bug
  color: d73a4a
  description: "Something isn't working"
  aliases: []
- name: chef
  color: 14C268
  description: Chef
  aliases: []
- name: codecov
  color: 9999B8
  description: CodeCov
  aliases: []
- name: datadog
  color: 632ca6
  description: 'Datadog: Cloud Monitoring as a Service'
  aliases: []
- name: dependencies
  color: 0366d6
  description: 'Pull requests that update a dependency file'
  aliases: []
- name: devto
  color: '000000'
  description: Dev.to
  aliases: []
- name: docker
  color: 0052CC
  description: Docker
  aliases: []
- name: documentation
  color: 0075ca
  description: 'Improvements or additions to documentation'
  aliases: []
- name: duplicate
  color: cfd3d7
  description: 'This issue or pull request already exists'
  aliases: []
- name: enhancement
  color: a2eeef
  description: 'New feature or request'
  aliases: []
- name: github
  color: '000000'
  description: GitHub
  aliases: []
- name: github_actions
  color: '000000'
  description: 'Pull requests that update GitHub Actions code'
  aliases: []
- name: github_app
  color: 08B4B2
  description: 'GitHub App'
  aliases: []
- name: 'good first issue'
  color: 7057ff
  description: 'Good for newcomers'
  aliases: []
- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'
  aliases: []
- name: invalid
  color: e4e669
  description: "This doesn't seem right"
  aliases: []
- name: javascript
  color: FBCA04
  description: 'Pull requests that update JavaScript code'
  aliases: []
- name: labels
  color: fef2c0
  description: labels
  aliases: []
- name: markdown
  color: 1F0135
  description: 'Pull requests that update Markdown code'
  aliases: []
- name: openai
  color: 03D5EB
  description: OpenAI
  aliases: []
- name: pagerduty
  color: 0E8A16
  description: PagerDuty
  aliases: []
- name: pulumi
  color: BF347D
  description: Pulumi
  aliases: []
- name: qiita
  color: 55c500
  description: Qiita
  aliases: []
- name: question
  color: d876e3
  description: 'Further information is requested'
  aliases: []
- name: rails
  color: B60205
  description: 'Ruby on Rails'
  aliases: []
- name: react
  color: 6B9A67
  description: React
  aliases: []
- name: ruby
  color: B60205
  description: Ruby
  aliases: []
- name: size/L
  color: A14C05
  description: 'https://github.com/apps/pull-request-size'
  aliases: []
- name: size/M
  color: 7F7203
  description: 'https://github.com/apps/pull-request-size'
  aliases: []
- name: size/S
  color: 5D9801
  description: 'https://github.com/apps/pull-request-size'
  aliases: []
- name: size/XL
  color: 7AE2C1
  description: 'ttps://github.com/apps/pull-request-size'
  aliases: []
- name: size/XS
  color: 3CBF00
  description: 'https://github.com/apps/pull-request-size'
  aliases: []
- name: size/XXL
  color: d93f0b
  description: 'ttps://github.com/apps/pull-request-size'
  aliases: []
- name: skip-push
  color: ededed
  description: null
  aliases: []
- name: slack
  color: 76A2DD
  description: Slack
  aliases: []
- name: td-agent
  color: 358FF2
  description: 'Treasure Agent (td-agent)'
  aliases: []
- name: terraform
  color: 0C0BAB
  description: Terraform
  aliases: []
- name: textlint
  color: 85825B
  description: textlint
  aliases: []
- name: wontfix
  color: ffffff
  description: 'This will not be worked on'
  aliases: []
- name: wordpress
  color: 0052CC
  description: WordPress
  aliases: []
- name: yaml
  color: 9B3520
  description: YAML
  aliases: []
