repository:
  name: qiita-articles
  description: mziyut's qiita-articles
  homepage: https://qiita.com/mziyut
  topics: qiita, markdown, qiita-cli, articles
  private: true
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: articles
    color: 55c550
    description: Qiita articles
  - name: AWS
    color: E08634
    description: Amazon Web Services
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: Datadog
    color: 632ca6
    description: Datadog
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: GitHub Actions
    color: 1A61E2
  - name: GitHub App
    color: 08B4B2
  - name: GitHub
    color: 000000
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: JavaScript
    color: FBCA04
  - name: merge when green
    color: 2cbe4e
    description: See: https://github.com/phstc/probot-merge-when-green/
  - name: question
    color: d876e3
    description: Further information is requested
  - name: Slack
    color: 76A2DD
  - name: wontfix
    color: ffffff
    description: This will not be worked on

milestones:
  - title: 2023
    description:
    state: open

branches:
  - name: main
