name: Blog - pull articles

on:
  schedule:
    - cron: '*/20 * * * *'
  push:
    paths:
      - '.github/workflows/blog_pull_articles.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pull_articles:
    uses: hatena/hatenablog-workflows/.github/workflows/pull.yaml@v1
    with:
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
