name: Blog - Test

on:
  push:
    paths:
      - 'blog/**'
      - '.github/workflows/blog_test.yml'

permissions:
  contents: read
  packages: read
  issues: read
  deployments: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  textlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace blog textlint

  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace blog prettier

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace blog build
      - uses: cloudflare/pages-action@v1
        if: github.ref != 'refs/heads/main'
        with:
          apiToken: ${{ secrets.BLOG_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.BLOG_CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog
          directory: ./blog/_book/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
