name: Blog - publish articles

on:
  push:
    branches:
      - main
    paths:
      - 'blog/**'
      - '.github/workflows/blog_publish_articles.yml'
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace blog build
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.BLOG_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.BLOG_CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog
          directory: ./blog/_book/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
