name: Dev.to - pull articles

on:
  schedule:
    - cron: '*/20 * * * *'
  push:
    paths:
      - '.github/workflows/devto_pull_articles.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pull_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace devto run dev init -p
        env:
          DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
          DEVTO_REPO: mziyut/articles
      - run: yarn workspace devto format:fix
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Pull articles
          delete-branch: true
          title: Pull articles
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: mziyut
          branch: create-pull-request/patch-pull-articles-devto
          add-paths: |
            devto/posts/*
          labels: |
            articles
            devto
