name: Dev.to - publish articles

on:
  push:
    branches:
      - main
    paths:
      - 'devto/**'
      - '.github/workflows/devto_publish_articles.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: devto
      url: https://dev.to/mziyut
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace devto run dev push
        env:
          DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
          DEVTO_REPO: mziyut/articles
      - run: yarn workspace devto format:fix
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Publish articles
          delete-branch: true
          title: Publish articles
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: mziyut
          branch: create-pull-request/patch-publish-articles-devto
          add-paths: |
            devto/posts/*
          labels: |
            articles
            automerge
            devto
