name: Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assignAuthor:
    name: Assign author to issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to issue
        uses: technote-space/assign-author@v1
