name: Sync labels

on:
  push:
    paths:
      - '.github/labels.yaml'
      - '.github/workflows/label_sync.yml'
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  label_sync:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yaml
          delete-other-labels: true
          dry-run: ${{ github.ref != 'refs/heads/main' }}
