name: Publish articles

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: production
      url: https://qiita.com/mziyut
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn run qiita publish --all
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
      - run: yarn run format:fix
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Publish articles
          delete-branch: true
          title: Publish articles
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: mziyut
