name: Pull request

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  assignAuthor:
    name: Assign author to Pull request
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to Pull request
        uses: technote-space/assign-author@v1
