name: Qiita - Test

on:
  push:
    paths:
      - 'qiita/**'
      - '.github/workflows/qiita_test.yml'

permissions:
  contents: read
  packages: read
  issues: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  textlint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace qiita textlint:codecov
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: yarn workspace qiita textlint

  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace qiita prettier
